version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rhorizon
      POSTGRES_USER: rhorizon
      POSTGRES_PASSWORD: rhorizon
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      FLASK_DEBUG: "true"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rhorizon
      DB_USER: rhorizon
      DB_PASSWORD: rhorizon
      DB_SSLMODE: disable
      AWS_REGION: eu-west-3
      S3_BUCKET_NAME: ""  # set your bucket in cloud
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
  build:
    context: .
    dockerfile: Dockerfile.frontend
  depends_on:
    backend:
      condition: service_healthy
  ports:
    - "80:80"
